---
- hosts: dev
  remote_user: ubuntu
  become: yes

  tasks:
  - name: Install AWS cli
    apt: update_cache=yes name=awscli state=present

  - name: Install nginx
    apt: name=nginx state=present
  - name: Copy nginx vhost config
    template: src=blog.example.com.conf dest=/etc/nginx/sites-available/blog.example.com.conf
  - name: Create symlink for nginx vhost
    file: src=/etc/nginx/sites-available/blog.example.com.conf dest=/etc/nginx/sites-enabled/default state=link
    notify: restart nginx

  - name: Install php-fpm
    apt:
      name: ['php{{ php_version }}', 'php{{ php_version }}-fpm', 'php{{ php_version }}-mysql']
      state:  present
  - name: Change php-fpm config
    lineinfile: path=/etc/php/{{ php_version }}/fpm/pool.d/www.conf regexp='^listen = /run/php/' line='listen = /var/run/php/wordpress.sock' backup=yes
    notify: restart php-fpm

  - name: Download WordPress
    get_url: url=https://wordpress.org/latest.tar.gz dest=/tmp/wordpress.tar.gz
    register: download_wordpress
  - name: Extract WordPress
    unarchive: remote_src=yes src=/tmp/wordpress.tar.gz dest=/var/www/html/ extra_opts='--strip-components=1'
    when: download_wordpress.changed
  - name: Change ownership of WordPress directory
    file: path=/var/www/html recurse=yes owner=www-data group=www-data
    notify: restart php-fpm

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted enabled=yes

    - name: restart php-fpm
      service: name=php{{ php_version }}-fpm state=restarted enabled=yes

